apps/users_app/urls.py
from django.conf.urls import url
from . import views          
urlpatterns = [
    # below routes are rendering templates
    url(r'^$', views.index, name='my_index'),
    url(r'^new$', views.new, name='my_new'),
    # below routes is for post/update actions for User model in db
    url(r'^create$', views.create, name='my_create'),
    url(r'^(?P<id>\d+)/update$', views.update, name='my_update'),
    # # below render individual data
    url(r'^(?P<id>\d+)/edit$', views.edit, name='my_edit'),
    url(r'^(?P<id>\d+)/destroy$', views.destroy, name='my_destroy'),
    url(r'^(?P<id>\d+)$', views.show, name='my_show')
]

restful_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/', include('apps.users_app.urls', namespace='users')),
]

apps/users_app/models.py
from __future__ import unicode_literals
import re
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
# models
class UserManager(models.Manager):
  def validate_create(self, post_data):
    errors = []
    if len(post_data['fname']) < 2:
      errors.append("User first name should be more than 2 characters")
    if len(post_data['lname']) < 2:
      errors.append("User last name should be more than 2 characters")
    if not re.match(EMAIL_REGEX, post_data['email']):
      errors.append("invalid email") 
    #  existing email check
    else:
      if len(self.filter(email=post_data['email'])) > 0:
        errors.append("email already in use")
      else:
        return self.create(
          firstname = post_data['fname'],
          lastname = post_data['lname'],
          email = post_data['email'].lower()
        )
    return errors
    
  def validate_update(self, post_data, user_id):
    errors = []

    if len(post_data['fname']) < 2:
      errors.append("User first name should be more than 2 characters")
    if len(post_data['lname']) < 2:
      errors.append("User last name should be more than 2 characters")
    
    check = self.get(id=user_id)
    if check.email != post_data['email']:
      print('inside first if')
      if not re.match(EMAIL_REGEX, post_data['email']):
        errors.append("invalid email") 
      #  existing email check
      else:
        users = self.filter(email = post_data['email'].lower())
        if users:
          errors.append("email already in use")
    if not errors:
      print('inside second if')
      try:
        check.firstname = post_data['fname']
        check.lastname = post_data['lname']
        check.email = post_data['email'].lower()
        check.save()
        return check
      except:
        pass

    return errors

class User(models.Model):
  firstname = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)
  email = models.CharField(max_length=255)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  objects = UserManager()
  # def __str__(self):
  #   return "<User object: {} {} {}>".format(self.firstname, self.lastname, self.email)

apps/users_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from .models import *
from django.contrib.messages import error


# the index function is called when root is visited
# below methods render
def index(request):
    context = {
        "users": User.objects.all()
    }
    return render(request,"users_app/index.html", context)

def new(request):
    return render(request,"users_app/new.html")

def show(request, id):
    context = {
       "user" : User.objects.get(id=id)
    }
    return render(request,"users_app/show.html", context)

def edit(request, id):
    context = {
       "user" : User.objects.get(id=id)
    }
    return render(request,"users_app/edit.html", context)

def destroy(request, id):
    d = User.objects.get(id=id)
    d.delete()
    return redirect(reverse('users:my_index'))

# form methods

def update(request, id):
    if request.method == "POST":
        result = User.objects.validate_update(request.POST, user_id=id)
        if type(result) == User:
            return redirect(reverse('users:my_show', kwargs={'id':id}))
        for err in result:
            error(request, err, 'red')        
    return redirect(reverse('users:my_edit', kwargs={'id':id}))
    

def create(request):
    result = User.objects.validate_create(request.POST)
    if type(result) == User:
        return redirect(reverse('users:my_index'))
    else:
        for err in result:
            error(request, err, 'red')
            return redirect(reverse('users:my_new'))
    

apps/users_app/templates/users_app/edit.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'users_app/css/style.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <h1>Edit User</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form action="{% url 'users:my_update' id=user.id %}" method="post">
            {% csrf_token %} First name:
            <br>
            <input type="text" name="fname" value={{user.firstname}}>
            <br> Last name:
            <br>
            <input type="text" name="lname" value={{user.lastname}}>
            <br> Email:
            <br>
            <input type="text" name="email" value={{user.email}}>
            <br>
            <br>
            <input type="submit" value="Update">
            <br>
        </form>
        <a href="{% url 'users:my_show' id=user.id %}">Show</a> | 
        <a href="{% url 'users:my_index' %}">Go back</a>
    </body>

</html>

apps/users_app/templates/users_app/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'users_app/css/style.css' %}" media="screen" title="no title"  charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->   
</head>
<body>
    <h1>Users</h1>
    <table>
        <tr>
            <th>id</th>
            <th>Full Name</th>
            <th>Email</th>
            <th>Created At</th>
            <th>Actions</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{user.id}}</td>
            <td>
                <a href="{% url 'users:my_show' id=user.id %}">{{user.firstname}} {{user.lastname}}</a>
            </td>
            <td>{{user.email}}</td>
            <td>{{user.created_at}}</td>
            <td>
                <a href="{% url 'users:my_show' id=user.id %}">Show</a>
                <a href="{% url 'users:my_edit' id=user.id %}">Edit</a>
                <a href="{%url 'users:my_destroy' id=user.id %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>      
    <a href="{% url 'users:my_new' %}">Add a new user</a>

</body>

</html>

apps/users_app/templates/users_app/new.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'users_app/css/style.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <h1>Add a new user</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form action="{%url 'users:my_create' %}" method="post">
            {% csrf_token %}
            First name:<br>
            <input type="text" name="fname" value="">
            <br>
            Last name:<br>
            <input type="text" name="lname" value="">
            <br>
            Email:<br>
            <input type="text" name="email" value="">
            <br><br>
            <input type="submit" value="Create">
            <br>
        </form> 
        <a href="{% url 'users:my_index' %}">Go back</a>
    </body>

</html>

apps/users_app/templates/users_app/show.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'usres_app/css/style.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <h1>User</h1>
        <p>Full Name: {{user.firstname}} {{user.lastname}}</p>
        <p>Email: {{user.email}}</p>
        <p>Created At: {{user.created_at}}</p>
        <br>
        <br>
        <a href="{% url 'users:my_edit' id=user.id %}">Edit</a> | 
        <a href="{%url 'users:my_destroy' id=user.id %}">Delete</a>
    </body>

</html>